### ISSUE TITLE
maybe add page for live status of all public nodes?

### ISSUE THREAD

**Issue by mrrovot** [turtlecoin/turtleturtle.org#18]
Used @brandonlehmann code and api to create a page that shows live status of all turtle public nodes.
http://trtlnodes.surge.sh/ 

Right now couldn't find many public nodes but hopefully in the near future more will become available.
Please let me know if this can be integrated, its 2 js files and 1 html that fits the `{{ content }}` of the layout folder.

**Comment by RocksteadyTC** [comment]
https://github.com/turtlecoin/turtlecoin-nodes-json

**Comment by mrrovot** [comment]
@RocksteadyTC from turtlenode site `Effective 2018-06-16: Public access to the individual nodes is no longer permitted to better control traffic flow and load balancing. Please use one of the region load balancers or the public.turtlenode.io hostname.`  

I could still add all the individual nodes for informational purposes.

**Comment by mrrovot** [comment]
If this gets approved into turtleturtle.org maybe we could link to it from nodes.turtlecoin.lol, could be useful shortcut to see status of nodes

**Comment by RocksteadyTC** [comment]
why close, it's a good idea

**Comment by mrrovot** [comment]
Oh I thought there was no interest for this, let me know where can I add it. 
right now is at trtlnodes.surge.sh

**Comment by brandonlehmann** [comment]
Yes. It’s possible. Just filter the results from display. Also... the update timer really shouldn’t be much faster than block target time 30s.

**Comment by mrrovot** [comment]
I will hide nodes that are not sycned and update the table every 31 secs

**Comment by mrrovot** [comment]
is turtleturtle.org a jekyll site?

**Comment by RocksteadyTC** [comment]
yes

**Comment by mrrovot** [comment]
now only shows synced nodes as well as the nodes from turtlenode.net 
https://trtlnodes.surge.sh/

how do I commit this? it's one html file that will fit the `{{content}}` section of turtleturtle repo and 2 js files

the code is also here:
https://github.com/mrrovot/public-nodes-statuses

**Comment by RocksteadyTC** [comment]
hmm... I'm not sure the best way to include it in there. I'd love to have it all on the same page, but markdown complicates that somewhat. What are the objections to just using straight up HTML and divs?

**Comment by mrrovot** [comment]
right now its using just html and divs, its all in the index.html under <section>, that section will fit the current turtleturtle.org page

On the turtleturtle I only see a markdown file so not sure how to add the html of the public nodes table?

**Comment by mrrovot** [comment]
I think I saw it now , it's in the the turltleturtle.html , I will try to add it tonight

**Comment by RocksteadyTC** [comment]
OK cool, let me know if you run in to trouble, markdown can be a little weird

**Comment by mrrovot** [comment]
Will try to refactor this during the weekend to make it work with the Turtlecoin-rpc and get the nodes from https://github.com/turtlecoin/turtlecoin-nodes-json

**Comment by RocksteadyTC** [comment]
@mrrovot we are getting PR's to publicnodes.json, is there a chance you have something workable we can use to pull from https://github.com/turtlecoin/turtlecoin-nodes-json

**Comment by mrrovot** [comment]
I didn't have much time lately, I will get to this in this weekend

**Comment by mrrovot** [comment]
I am still trying to achieve this, problem I get is that most public nodes can't be called from the browser because of CORS

**Comment by brandonlehmann** [comment]
Run it through https://api.turtlenode.io/someiphere/porthere/getinfo it should answer with cors header for anything you throw at it

**Comment by brandonlehmann** [comment]
Example https://api.turtlenode.io/node-1.sin.turtlenode.io/11898/getinfo

**Comment by mrrovot** [comment]
on it, thanks

**Comment by mrrovot** [comment]
this worked!, will clean the code and do a pull request later tonight

**Comment by brandonlehmann** [comment]
Awesome!

**Comment by mrrovot** [comment]
I see it was merged to turtleturtle.org and it works,  but for some reason the nodes will only load after about a minute, will try to find what can cause that because I don't see anything obvious so far

**Comment by zpalmtree** [comment]
Perhaps you are waiting for all the apis to respond before displaying any data, instead of loading the table incrementally and in parallel?

**Comment by mrrovot** [comment]
I think that might be it, will try to fix tomorrow

**Comment by brandonlehmann** [comment]
The cheap version is adding http://trtl.nodes.pub/ to turtleturtle which has been done :)
