### ISSUE TITLE
[URGENT] The URL is expired/broken

### ISSUE THREAD

**Issue by Sajo8** [turtlecoin/turtleturtle.org#79]
http://turtleturtle.org/ is broken

**Comment by Watt3r** [comment]
I can donate one of my domains, such as trtlco.in Or turtle-coin.com for this

**Comment by Sajo8** [comment]
@RocksteadyTC check this out

**Comment by Sajo8** [comment]
Rocksteady renewed it, http://turtleturtle.org works now

**Comment by RocksteadyTC** [comment]
All fixed :D
